import React from 'react';
import { createRoot } from 'react-dom/client';
import { CheckCircle, Clock, Heart, MessageCircle, Shield, Sparkles, Star, Zap } from 'lucide-react';
import './styles.css';

const WHATSAPP_BASE = 'https://wa.me/5521981107606';
const makeWa = (text: string) => `${WHATSAPP_BASE}?text=${encodeURIComponent(text)}`;
const WHATSAPP_DEFAULT = makeWa('Olá, quero agendar uma sessão');

const services = [{ title: 'Drenagem Linfática', description: 'Reduz inchaço, retenção de líquido e melhora a circulação. Sensação de leveza imediata.', duration: '40 a 50 minutos', cta: 'Quero agendar drenagem', link: makeWa('Olá, quero agendar uma drenagem linfática'), icon: Sparkles }, { title: 'Massagem Modeladora', description: 'Técnica intensa para redução de medidas e definição corporal.', duration: '40 a 50 minutos', cta: 'Quero modelar meu corpo', link: makeWa('Olá, quero agendar uma massagem modeladora'), icon: Zap }, { title: 'Massagem Relaxante', description: 'Alívio de estresse, tensão muscular e ansiedade.', duration: '40 a 50 minutos', cta: 'Quero relaxar', link: makeWa('Olá, quero agendar uma massagem relaxante'), icon: Heart }];
const benefits = ['Atendimento personalizado para seu objetivo', 'Resultados perceptíveis desde a primeira sessão', 'Técnicas profissionais e seguras', 'Sessões rápidas, ideais para rotina corrida', 'Ambiente confortável e acolhedor'];
const testimonials = [{ name: 'Ana Carolina', text: 'Saí me sentindo muito mais leve já na primeira sessão. Incrível!' }, { name: 'Juliana M.', text: 'A modeladora é maravilhosa! Já percebi diferença nas medidas em poucas sessões.' }, { name: 'Fernanda S.', text: 'Ambiente super aconchegante e atendimento impecável. Virei cliente fiel.' }, { name: 'Mariana P.', text: 'Sofria muito com retenção de líquido, a drenagem mudou minha vida.' }, { name: 'Camila R.', text: 'Melhor investimento que fiz em mim mesma. Relaxante perfeita após a semana.' }];
const qualifications = ['Sente inchaço ou retenção de líquido', 'Quer reduzir medidas', 'Vive com dores ou tensão muscular', 'Busca relaxamento e bem-estar'];

function WhatsAppButton({ href, children, variant = 'solid' }: { href: string; children: React.ReactNode; variant?: 'solid' | 'outline' }) {
  return <a className={`button ${variant}`} href={href} target="_blank" rel="noopener noreferrer"><MessageCircle />{children}</a>;
}

function App() {
  return <><main><section className="hero"><div className="heroText"><p className="eyebrow">Glow & Go</p><h1>Transforme seu corpo e sua mente em apenas <span>50 minutos</span></h1><p>Atendimentos personalizados de drenagem, modeladora e relaxante com resultados visíveis desde a primeira sessão.</p><WhatsAppButton href={WHATSAPP_DEFAULT}>Agendar pelo WhatsApp</WhatsAppButton></div><div className="heroCard"><div className="circle"><Sparkles /></div><strong>Drenagem · Modeladora · Relaxante</strong><span>Atendimento por agendamento</span></div></section><section id="servicos" className="section alt"><p className="eyebrow">Serviços</p><h2>Nossos serviços</h2><p>Escolha o tratamento ideal para você</p><div className="services">{services.map((service) => { const Icon = service.icon; return <article key={service.title}><div className="icon"><Icon /></div><h3>{service.title}</h3><p>{service.description}</p><span><Clock />{service.duration}</span><WhatsAppButton href={service.link}>{service.cta}</WhatsAppButton></article>; })}</div></section><section className="section"><p className="eyebrow">Benefícios</p><h2>Por que esse atendimento funciona?</h2><div className="checks">{benefits.map((item) => <article key={item}><CheckCircle /><span>{item}</span></article>)}</div></section><section className="section alt"><p className="eyebrow">Prova social</p><h2>O que nossas clientes dizem</h2><div className="testimonials">{testimonials.map((item) => <article key={item.name}><div>{Array.from({ length: 5 }).map((_, index) => <Star key={index} />)}</div><p>“{item.text}”</p><strong>{item.name}</strong></article>)}</div></section><section className="section"><p className="eyebrow">Para você</p><h2>Esse atendimento é para você que:</h2><div className="checks compact">{qualifications.map((item) => <article key={item}><Shield /><span>{item}</span></article>)}</div><div className="center"><WhatsAppButton href={WHATSAPP_DEFAULT}>Agendar minha sessão</WhatsAppButton></div></section><section className="cta"><h2>Pronta para começar hoje?</h2><p>Agende sua sessão agora e sinta a diferença.</p><WhatsAppButton href={WHATSAPP_DEFAULT}>Agendar agora no WhatsApp</WhatsAppButton></section></main><footer>© {new Date().getFullYear()} — Todos os direitos reservados</footer><a className="float" href={WHATSAPP_DEFAULT} target="_blank" aria-label="WhatsApp"><MessageCircle /></a></>;
}

createRoot(document.getElementById('root')!).render(<App />);
